# Generated by Django 4.1.6 on 2023-04-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.CharField(max_length=128, verbose_name='Название Кинотеатра')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, upload_to='media', verbose_name='Превью')),
                ('image_detail', models.ImageField(blank=True, upload_to='media', verbose_name='Фото кинотеатра')),
                ('info', models.TextField(max_length=5000, verbose_name='Информация')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='CityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('row_count', models.PositiveIntegerField()),
                ('col_count', models.PositiveIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128, verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производствы',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('date', models.DateTimeField()),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('title_img', models.ImageField(blank=True, upload_to='media')),
                ('detail_img', models.ImageField(blank=True, upload_to='media')),
                ('premiere', models.DateTimeField(verbose_name='премьера')),
                ('duration', models.PositiveIntegerField(null=True)),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('genre', models.ManyToManyField(to='myapp.genre', verbose_name='Жанр')),
                ('production', models.ManyToManyField(to='myapp.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citylocation', verbose_name='Город'),
        ),
    ]
