# Generated by Django 4.1.6 on 2023-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='cinema',
        ),
        migrations.AddField(
            model_name='show',
            name='cinema',
            field=models.ManyToManyField(to='myapp.cinema', verbose_name='Кинотеатр'),
        ),
    ]
