# Generated by Django 4.1.6 on 2023-04-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_detail_img_movie_img_remove_movie_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='movie_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.movie'),
        ),
    ]
