# Generated by Django 4.1.6 on 2023-04-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hall_movie_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='movie_show',
        ),
        migrations.CreateModel(
            name='ShowMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_show', models.TimeField(default='08:00')),
                ('movie_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='show_movie',
            field=models.ManyToManyField(to='myapp.showmovie'),
        ),
    ]
