# Generated by Django 4.1.6 on 2023-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
