# Generated by Django 4.1.6 on 2023-02-18 19:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cinemas_cityslocation_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemas',
            options={'verbose_name': 'Кинотеатр', 'verbose_name_plural': 'Кинотеатры'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='cityslocation',
            old_name='city',
            new_name='name',
        ),
    ]
