# Generated by Django 4.1.6 on 2023-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
