# Generated by Django 4.1.6 on 2023-04-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_seat_is_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocation',
            name='name',
            field=models.CharField(default='Караганда', max_length=128, unique=True, verbose_name='Город'),
        ),
    ]
