# Generated by Django 4.1.6 on 2023-04-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_citylocation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showmovie',
            old_name='movie_show',
            new_name='movie',
        ),
    ]
