# Generated by Django 4.1.6 on 2023-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_movie_show_showmovie_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img_detail',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
